文档写到现在也没有提及到错误信息，但是你也能从之前的例子中看到一些错误的定义和捕获，python至少有两种可区分的错误：语法错误(error)和程序异常(exception)

### 8.1. 语法错误(Syntax Errors)
语法，也就是为人所知的解析错误，也是你在学习Python过程中抱怨最多的事情

```
>>> while True print('Hello world')
  File "<stdin>", line 1
    while True print('Hello world')
                   ^
SyntaxError: invalid syntax
```
解析器会将出错的行重新打印出来，并且使用一个小小的箭头指向最初检测到错误的位置，错误是发生在(至少检测是这样)箭头指向位置之前，在上述例子中，检测到的错误发生在print()，是因为在print之前缺少冒号，文件名和行号也打印了，这样就能精确定位错误，方便查找错误
### 8.2 异常(Exception)
即使语句和表达式的语法是正确的，也可能在执行的时候产生一个错误，在执行期间检测到的错误叫做异常，当然异常也不是百分百会让程序奔溃，你将很快学会如何在python编程中处理它们。大部分的异常不是由程序控制的，但是，异常结果都是如下所示的模式：

```
>>> 10 * (1/0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ZeroDivisionError: division by zero
>>> 4 + spam*3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'spam' is not defined
>>> '2' + 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Can't convert 'int' object to str implicitly
```
最后一行的错误信息会指明发生了什么， 异常的来源形形色色，打印异常信息的时候也会带上异常的类型，例子中的异常类型就是ZeroDivisionError，NameError和TypeError。表示异常类型的字符串和在python内置异常定义的名称是一致的，这对于所有的内置异常来说是正确的，但是对于用户定义的异常来说就有可能不太对(虽然这是公约)。标准的异常名称是内置的标识符(不包括预留字)

剩下的信息是基于异常类型的详细信息以及是什么造成异常的

### 8.3 异常处理
对于可能发生的已知异常可以进行处理，请看下面的例子，要求用户输入一个整数，当用户输入一个非法的整数时，则捕获该异常，并且允许用户终端程序（使用Control-C或者任意的操作系统支持的方式），注意： 用户生成的中断在程序中表示的抛出一个叫做 KeyboardInterrupt的异常

```
>>> while True:
...     try:
...         x = int(input('Please enter a number: '))
...         break
...     except ValueError:
...         print('Oops! That was no valid number. Try again...')
...
```
try语句工作流程如下：
* 首先， try子句(在try和except之间的语句)已经执行
* 如果没有异常产生，那么except子句就不执行并且
